// Single source of truth for the Work / Portfolio page's video dataset.
// All portfolio videos are unlisted on YouTube, so they can't be discovered
// via the Data API (playlistItems.list only returns public uploads) — they
// are embedded directly by ID instead, which works fine for unlisted videos.

export const VIDEOS = [
  {
    id: "BJ6unInyICs",
    title: "Shoot (Charlie)",
    client: "Charlie",
    cat: "Video Production",
    dur: "1:04",
    year: "2024",
    featured: false,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "lMbQDIXXbCY",
    title: "Shoot 2 (Charlie Residency)",
    client: "Charlie",
    cat: "Video Production",
    dur: "1:38",
    year: "2024",
    featured: false,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "c-lPgwJ7SDY",
    title: "Shoot (Estate 1 city view)",
    client: "Estate 1 city view",
    cat: "Real Estate",
    dur: "1:01",
    year: "2024",
    featured: true,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "FQAntfx06hE",
    title: "shoot (fibbi)",
    client: "Fibbi",
    cat: "Video Production",
    dur: "1:14",
    year: "2024",
    featured: false,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "XXyMVB2Fbcw",
    title: "Shoot (Estate 1 City Comfort)",
    client: "Estate 1 City Comfort",
    cat: "Video Production",
    dur: "1:16",
    year: "2024",
    featured: false,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "7oeEJdCQniw",
    title: "Shoot 2 (Estate 1 City Comfort)",
    client: "Estate 1 City Comfort",
    cat: "Video Production",
    dur: "0:25",
    year: "2023",
    featured: false,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "HSSyAMkNc60",
    title: "Shoot 3 (Estate 1 City Comfort)",
    client: "Estate 1 City Comfort",
    cat: "Video Production",
    dur: "0:31",
    year: "2023",
    featured: false,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "f3bd-f_9v0M",
    title: "Shoot 4 (Estate 1 City Comfort)",
    client: "Estate 1 City Comfort",
    cat: "Video Production",
    dur: "1:15",
    year: "2024",
    featured: false,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "QpgKZN1v4m0",
    title: "Ai Video (Paari Builders)",
    client: "Paari Builders and developers (Reel)",
    cat: "Video Production",
    dur: "0:26",
    year: "2026",
    featured: false,
    desc: "An immersive AI-generated launch film combining futuristic aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "qwKHHtlSidE",
    title: "development Ai Video (Paari Builders)",
    client: "Paari Builders and developers (Reel)",
    cat: "Video Production",
    dur: "0:29",
    year: "2026",
    featured: false,
    desc: "An immersive AI-generated launch film combining futuristic aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "WKPtIAZCAYI",
    title: "Shoot (Paari Builders)",
    client: "Paari Builders and developers (Reel)",
    cat: "Video Production",
    dur: "0:38",
    year: "2026",
    featured: false,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "nz-DDAjjXqw",
    title: "City View 2 (Estate 1)",
    client: "Estate 1 City View (Reel)",
    cat: "Real Estate",
    dur: "0:44",
    year: "2024",
    featured: false,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "-cGQArxuV-U",
    title: "Drone (fibbi)",
    client: "Fibbi (Reels)",
    cat: "Video Production",
    dur: "0:19",
    year: "2024",
    featured: false,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "Hm2SOjqJWpg",
    title: "development Ai Video (City Comfort)",
    client: "City Comfort (Reel)",
    cat: "Video Production",
    dur: "0:35",
    year: "2025",
    featured: false,
    desc: "An immersive AI-generated launch film combining futuristic aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "Ykvqo85M6j0",
    title: "Video Shoot (Punjabi Icon)",
    client: "Punjabi Icon (Estate 1)",
    cat: "Real Estate",
    dur: "0:42",
    year: "2025",
    featured: false,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "E0Rwceux6z4",
    title: "Duo model Video (Burj ul ameen)",
    client: "Burj Al Ameen",
    cat: "Video Production",
    dur: "1:25",
    year: "2025",
    featured: false,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "szGTA31KCgM",
    title: "Work Shop (Fazil Maniya)",
    client: "Fazil Maniya",
    cat: "Complete Event Management",
    dur: "1:28",
    year: "2025",
    featured: false,
    desc: "A high-energy event film combining candid workshop moments, interactive learning sequences, and cinematic storytelling.",
  },
  {
    id: "3tY0Qx7-u6A",
    title: "Work Shop 2 (Fazil Maniya)",
    client: "Fazil Maniya",
    cat: "Complete Event Management",
    dur: "3:26",
    year: "2026",
    featured: false,
    desc: "A high-energy event film combining candid workshop moments, interactive learning sequences, and cinematic storytelling.",
  },
  {
    id: "oNExDxunv_o",
    title: "Disable Person Quota (SPDPA)",
    client: "SPDPA",
    cat: "Complete Event Management",
    dur: "3:32",
    year: "2024",
    featured: false,
    desc: "A polished public-sector wrap-up featuring seamless multi-camera coverage, smooth transitions, and a clean documentary-style edit.",
  },
  {
    id: "seMPIyDGJdk",
    title: "Nawabshah (SPDPA)",
    client: "SPDPA",
    cat: "Complete Event Management",
    dur: "5:12",
    year: "2025",
    featured: false,
    desc: "A polished public-sector wrap-up featuring seamless multi-camera coverage, smooth transitions, and a clean documentary-style edit.",
  },
  {
    id: "YC0LCLqEIn8",
    title: "SD (SPDPA)",
    client: "SPDPA",
    cat: "Complete Event Management",
    dur: "0:54",
    year: "2026",
    featured: false,
    desc: "A polished public-sector wrap-up featuring seamless multi-camera coverage, smooth transitions, and a clean documentary-style edit.",
  },
  {
    id: "c0_wwhTiIzc",
    title: "Production Video (G&D Nutrition)",
    client: "G&D Nutrition",
    cat: "Video Production",
    dur: "5:16",
    year: "2025",
    featured: false,
    desc: "A polished public-sector wrap-up featuring seamless multi-camera coverage, smooth transitions, and a clean documentary-style edit.",
  },
  {
    id: "a9TPiIdqzSU",
    title: "Day 1 (NIC)",
    client: "NIC",
    cat: "Complete Event Management",
    dur: "1:20",
    year: "2025",
    featured: false,
    desc: "A polished tech-ecosystem showcase featuring premium multi-camera event coverage, crisp keynote highlights, and seamless corporate editing.",
  },
  {
    id: "GucDWoERtjM",
    title: "Day 2 (NIC)",
    client: "NIC",
    cat: "Complete Event Management",
    dur: "1:03",
    year: "2025",
    featured: false,
    desc: "A polished tech-ecosystem showcase featuring premium multi-camera event coverage, crisp keynote highlights, and seamless corporate editing.",
  },
  {
    id: "BsVWDU4NdlM",
    title: "Day 3 (NIC)",
    client: "NIC",
    cat: "Complete Event Management",
    dur: "1:10",
    year: "2025",
    featured: false,
    desc: "A polished tech-ecosystem showcase featuring premium multi-camera event coverage, crisp keynote highlights, and seamless corporate editing.",
  },
  {
    id: "2Er-43mMpJc",
    title: "Day 4 (NIC)",
    client: "NIC",
    cat: "Complete Event Management",
    dur: "1:02",
    year: "2025",
    featured: false,
    desc: "A polished tech-ecosystem showcase featuring premium multi-camera event coverage, crisp keynote highlights, and seamless corporate editing.",
  },
  {
    id: "_HUbTMLrGO8",
    title: "Day 5 (NIC)",
    client: "NIC",
    cat: "Complete Event Management",
    dur: "1:34",
    year: "2025",
    featured: false,
    desc: "A polished tech-ecosystem showcase featuring premium multi-camera event coverage, crisp keynote highlights, and seamless corporate editing.",
  },
  {
    id: "l5ntZkHh2bQ",
    title: "SocialJockey PodCast (Murtuza Wahab Teaser)",
    client: "SocialJockey",
    cat: "Podcast",
    dur: "2:15",
    year: "2026",
    featured: false,
    desc: "A sleek in-studio podcast film combining a premium neon-lit ambiance, multi-camera switching, and intimate lifestyle storytelling.",
  },
  {
    id: "dKwYK6KlaXQ",
    title: "Shoot (Short) (Burj ul ameen residence)",
    client: "Burj ul ameen residence Reel",
    cat: "Video Production",
    dur: "0:24",
    year: "2025",
    featured: false,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "iLTusD9Y3cY",
    title: "Shoot (Short) (Burj ul ameen Shop)",
    client: "Burj ul ameen Shop Reel",
    cat: "Video Production",
    dur: "0:22",
    year: "2024",
    featured: false,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "PpnwmWQaTig",
    title: "Female Model reel (Burj al ameen)",
    client: "Burj al ameen Reel",
    cat: "Video Production",
    dur: "0:59",
    year: "2025",
    featured: false,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "8BwjaEm48Dg",
    title: "male Model reel (Burj al ameen)",
    client: "Burj al ameen Reel",
    cat: "Video Production",
    dur: "0:40",
    year: "2025",
    featured: false,
    desc: "A cinematic launch film combining aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "VNdz1Vfj7Jk",
    title: "Ai Model Video reel (Spectrum)",
    client: "Spectrum Developers Reel",
    cat: "AI Videos",
    dur: "0:58",
    year: "2026",
    featured: false,
    desc: "An immersive AI-generated launch film combining futuristic aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "fDAxGImVKOk",
    title: "Ai Video reel (Spectrum)",
    client: "Spectrum Developers Reel",
    cat: "Real Estate",
    dur: "0:26",
    year: "2026",
    featured: false,
    desc: "An immersive AI-generated launch film combining futuristic aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "oPfBu06WC2E",
    title: "Ai Video reel 2 (Spectrum)",
    client: "Spectrum Developers Reel",
    cat: "AI Videos",
    dur: "0:06",
    year: "2026",
    featured: false,
    desc: "An immersive AI-generated launch film combining futuristic aerial drone footage and lifestyle storytelling.",
  },
  {
    id: "I8Pihba4Ya0",
    title: "1 reel (Lamp Institute)",
    client: "Lamp Institute Reel",
    cat: "Commercial",
    dur: "0:59",
    year: "2026",
    featured: false,
    desc: "A premium studio promo showcasing a fully equipped, soundproof podcast room available for rent, featuring multi-cam setups and professional lighting.",
  },
  {
    id: "tnVf2Yk1P0I",
    title: "2 reel (Lamp Institute)",
    client: "Lamp Institute Reel",
    cat: "Commercial",
    dur: "0:13",
    year: "2026",
    featured: false,
    desc: "A premium studio promo showcasing a fully equipped, soundproof podcast room available for rent, featuring multi-cam setups and professional lighting.",
  },
  {
    id: "DQrKnU-98Aw",
    title: "1 reel (Off The Clock)",
    client: "Off The Clock Reel",
    cat: "Commercial",
    dur: "1:04",
    year: "2024",
    featured: false,
    desc: "A premium studio promo showcasing a fully equipped, soundproof podcast room available for rent, featuring multi-cam setups and professional lighting.",
  },
  {
    id: "R9kaBNjWGYg",
    title: "2 reel (Off The Clock)",
    client: "Off The Clock Reel",
    cat: "Commercial",
    dur: "1:13",
    year: "2024",
    featured: false,
    desc: "A premium studio promo showcasing a fully equipped, soundproof podcast room available for rent, featuring multi-cam setups and professional lighting.",
  },
  {
    id: "YMdcR8S-BMQ",
    title: "Animation Reel 1 (G&D Nutrition)",
    client: "G&D Nutrition",
    cat: "Social Media Management and Marketing",
    dur: "0:10",
    year: "2026",
    featured: false,
    desc: "A trendy social media product showcase driven by fast-paced motion design customization, dynamic text animations, and vibrant brand aesthetics.",
  },
  {
    id: "IA3TGzqPP94",
    title: "Animation Reel 2 (G&D Nutrition)",
    client: "G&D Nutrition",
    cat: "Social Media Management and Marketing",
    dur: "0:10",
    year: "2026",
    featured: false,
    desc: "A trendy social media product showcase driven by fast-paced motion design customization, dynamic text animations, and vibrant brand aesthetics.",
  },
  {
    id: "ekNTD9OLdbo",
    title: "1 reel (Sitare By Mehnaz)",
    client: "Sitara By Mehnaz",
    cat: "Social Media Management and Marketing",
    dur: "0:15",
    year: "2025",
    featured: false,
    desc: "A high-impact product animation reel combining hyper-realistic 3D rendering, dynamic camera movements, and seamless lifestyle pacing.",
  },
  {
    id: "KzpTzB3jbcE",
    title: "2 reel (Sitare By Mehnaz)",
    client: "Sitara By Mehnaz",
    cat: "Social Media Management and Marketing",
    dur: "0:22",
    year: "2025",
    featured: false,
    desc: "A high-impact product animation reel combining hyper-realistic 3D rendering, dynamic camera movements, and seamless lifestyle pacing.",
  },
  {
    id: "yncP145XgFk",
    title: "4 reel (Sitare By Mehnaz)",
    client: "Sitara By Mehnaz",
    cat: "Social Media Management and Marketing",
    dur: "0:17",
    year: "2025",
    featured: false,
    desc: "A high-impact product animation reel combining hyper-realistic 3D rendering, dynamic camera movements, and seamless lifestyle pacing.",
  },
  {
    id: "hDqoYR7HjpM",
    title: "5 reel (Sitare By Mehnaz)",
    client: "Sitara By Mehnaz",
    cat: "Social Media Management and Marketing",
    dur: "0:18",
    year: "2025",
    featured: false,
    desc: "A high-impact product animation reel combining hyper-realistic 3D rendering, dynamic camera movements, and seamless lifestyle pacing.",
  },
  {
    id: "mF0GiMgS4go",
    title: "6 reel (Sitare By Mehnaz)",
    client: "Sitara By Mehnaz",
    cat: "Social Media Management and Marketing",
    dur: "0:19",
    year: "2025",
    featured: false,
    desc: "A high-impact product animation reel combining hyper-realistic 3D rendering, dynamic camera movements, and seamless lifestyle pacing.",
  },
  {
    id: "24tYtA2UgC4",
    title: "Couple Trend (Bun Affair)",
    client: "Bun Affair",
    cat: "Social Media Management and Marketing",
    dur: "0:12",
    year: "2026",
    featured: false,
    desc: "A trendy social media product showcase driven by fast-paced motion design customization, dynamic text animations, and vibrant brand aesthetics.",
  },
  {
    id: "-W_r4j8NwAE",
    title: "Animation Post (Bun Affair)",
    client: "Bun Affair",
    cat: "Social Media Management and Marketing",
    dur: "0:09",
    year: "2026",
    featured: false,
    desc: "A trendy social media product showcase driven by fast-paced motion design customization, dynamic text animations, and vibrant brand aesthetics.",
  },
  {
    id: "jD1iY3Mqr8g",
    title: "Animation Post 2 (Bun Affair)",
    client: "Bun Affair",
    cat: "Social Media Management and Marketing",
    dur: "0:10",
    year: "2026",
    featured: false,
    desc: "A trendy social media product showcase driven by fast-paced motion design customization, dynamic text animations, and vibrant brand aesthetics.",
  },
  {
    id: "oTPwFLfger4",
    title: "Shoot (Bun Affair)",
    client: "Bun Affair",
    cat: "Social Media Management and Marketing",
    dur: "0:22",
    year: "2026",
    featured: false,
    desc: "A high-energy outdoor food film combining sizzling grill close-ups, fast-paced transitions, and dynamic street lifestyle storytelling.",
  },
  {
    id: "BMdRO-PyYog",
    title: "Animation Post 1 (Food Bar)",
    client: "Food Bar",
    cat: "Food",
    dur: "0:09",
    year: "2026",
    featured: false,
    desc: "A trendy social media product showcase driven by fast-paced motion design customization, dynamic text animations, and vibrant brand aesthetics.",
  },
  {
    id: "MsBWZdDZon0",
    title: "Animation Post pizza (Food Bar)",
    client: "Food Bar",
    cat: "Social Media Management and Marketing",
    dur: "0:09",
    year: "2026",
    featured: false,
    desc: "A trendy social media product showcase driven by fast-paced motion design customization, dynamic text animations, and vibrant brand aesthetics.",
  },
];
